### ISSUE TITLE
Add 2 more student details

### ISSUE THREAD

**Issue by ManjuVasanth** [mrsmanju/studentdetails#4]
{
      "id": 9,
      "name": "Adi",
      "phone": "2343354289",
      "courses": [
        "Java",
        "Ruby"
      ]
    },
    {
      "id": 10,
      "name": "Sun",
      "phone": "3455553489",
      "courses": [
        "Python",
        "Selenium"
      ]

**Comment by mrsmanju** [comment]
Sure Manju. Thanks for your contribution for the project.
